version: "3.7"

services:

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1235"
      POSTGRES_USER: "user"



