version: "3.7"

services:

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: "1235"
      POSTGRES_USER: "user"



